### ISSUE TITLE
click to scroll to an element

### ISSUE THREAD

**Issue by gingersoulrecords** [gingersoulrecords/SoulButtons#17]
GreenSock has some nifty scrollTo functionality that would be right at home with a Soulbutton. 

attributes: defaults

scrollToTarget: false
scrollToSpeed: 1
scrollToOffset: 0

**Comment by ideag** [comment]
added scrollto attribute that handles the actual setting and scroll speed.

**Comment by ideag** [comment]
Forgot the offset, so I'll have to add that in the next release.

**Comment by ideag** [comment]
change attributes for scrollto:
`scrollto` true/false
`scrollto-speed` default 0.5
`scrollto-offset` default 0
