### ISSUE TITLE
EDD integration - fix 'add-to-cart' style

### ISSUE THREAD

**Issue by gingersoulrecords** [gingersoulrecords/SoulButtons#18]
EDD has a purchase link shortcode

http://docs.easydigitaldownloads.com/article/229-purchaselink

that you can use to create purchase buttons for products and services. I'd like this button to inherit the default soulbutton styles (color, padding, borders) - as it has its own styles that come via EDD.

**Comment by gingersoulrecords** [comment]
Thought about this some more - I wonder if EDD would consider outputting a 'raw' purchase link without the default button styles. Or give us some JS events to work with? Could we mirror the button in a SoulButton style, etc.? Would appreciate your thoughts :)

**Comment by ideag** [comment]
I see a couple of ways doing it:

1. EDD `[purchase_link]` has a `class` attribute has a `class` attribute, so if you pass `soulbuttons` classess  to it, styles should be picked up automatically
2. I could add an `edd_id` attribute to SoulButtons, that would generate a SoulButton version of the purchase link.

**Comment by gingersoulrecords** [comment]
Let's with option 1
