### ISSUE TITLE
Can we set font-awesome/dashicons to 'on' by default?

### ISSUE THREAD

**Issue by gingersoulrecords** [gingersoulrecords/SoulButtons#26]
Hey, I was just adding a hamburger icon to 

https://wornstaging.wpengine.com/

's mobile menu (have a look!) and I was wondering where the icon was. This has happened to me on another site :) so it feels like it should be on by default, and people can turn it off for performance if they're not using the icon features. 

Thanks!

DB

**Comment by ideag** [comment]
Hey! I don't think turning them both on by default would be a good idea, but I think having dashicons on won't be too big a deal. Also, we can add some wording in the documentation to tell people to make sure they have the icon fonts turned on if they are using icon attribute.

**Comment by gingersoulrecords** [comment]
Remind me again? My only concern is that I'd like to place SoulButtons,
with icons included, into SoulSections templates that people can 'turn on.'
Though dashicons may be sufficient for this.

Is performance the issue?
