### ISSUE TITLE
Please prevent default on soulbutton links with a href ='#'

### ISSUE THREAD

**Issue by gingersoulrecords** [gingersoulrecords/SoulButtons#27]
Hello!

On the Soulbuttons animation click functions, can you insert 

function(e){
e.preventDefault();
}

To keep the URL from appending a hash?

Thx.

**Comment by gingersoulrecords** [comment]
Left a message in Slack about this - if that's the fix, please apply it at your convenience, thanks!

D

**Comment by ideag** [comment]
Hi, I am actually doing a prevent default, if you link to a hash. Do you have an example where that is not working?

**Comment by ideag** [comment]
The problem with just preventing default on hash links - if you do not also use scroll to, the links stop working at all.

**Comment by ideag** [comment]
also, I am not sure it is *always* good to prevent default on hash links. sometimes one might want the url in address bar to change, so that people could give direct links to parts of the site.

**Comment by gingersoulrecords** [comment]
Also fixed with an attribute
