### ISSUE TITLE
Apply 'targeteffect' styles on a conditional basis

### ISSUE THREAD

**Issue by gingersoulrecords** [gingersoulrecords/SoulButtons#28]
Hello!

I'm using SoulButtons' target & targetEffect attributes to position an off-canvas element (a menu). I'd like to be able to edit this menu in the Builder, so I need the AppendTo(body) and related styles (like fixed positioning, etc) only to apply outside of the Builder. The builder has an outer class of .fl-builder-edit, so that should be easy to check with jQuery.

Thx

**Comment by ideag** [comment]
again, I am already detecting `fl-builder-edit` class and not runing target/targeteffect related JS when in beaverbuilder mode. You can see this in my sample site: 

http://soulmagic.tnf.lt/sample-page-2/?fl_builder (beaver builder)
http://soulmagic.tnf.lt/sample-page-2/ (no builder)

In the first link, the primary menu is visible (not taken out by target/targeteffect
In the second one it is gone and is displayed if you click on the "rounded corners" button.
